---
title: 'EDS 221: Day 7 Activities'
author: "Clarissa Boyajian"
date: "8/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
```

## Task 1: 

#### Joins on birds:
```{r}
bird_observations <- read_csv(here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))

birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL")) %>% 
  filter(site_id %in% c("LI-W", "NU-C"))
```

#### Left join practice:
```{r}
birds_subset_2 <- left_join(x = birds_subset, y = sites, by = "site_id")
birds_left <- left_join(x = birds_subset_2, y = taxalist, by = "species_id")
```

#### Full join practice:
```{r}
birds_full <- full_join(x = birds_subset, y = sites, by = "site_id")
```

#### Inner join practice:
```{r}
birds_inner <- inner_join(x = birds_subset, y = taxalist, by = "species_id")

birds_inner_2 <- left_join(x = birds_subset, y = taxalist, by = "species_id")
```


## Task 2: Data wrangling and visualization with birds
```{r}
birds <- bird_observations %>% 
  rename(bird_obs_notes = notes)

birds_all_obs <- birds %>% 
  full_join(y = taxalist, by = "species_id") %>% 
  full_join(y = sites, by = "site_id") %>% 
  full_join(y = surveys, by = "survey_id") %>% 
  select(survey_date, common_name, park_name, bird_count)

birds_dates <- birds_all_obs %>% 
  mutate(survey_month = month(survey_date)) %>% 
  mutate(survey_month = as.factor(survey_month)) %>% 
  relocate(survey_month, .after = survey_date)

birds_summary <- birds_dates %>% 
  group_by(park_name, survey_month) %>% 
  summarise(total_counts = n()) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))

```





